import { TransactionRow, MeezanAccountInfo } from "../types";
import { formatNumber } from "./excelParser";

const generateHeaderSection = (accountInfo: MeezanAccountInfo) => {
  const opening = accountInfo.openingBalance ? formatNumber(accountInfo.openingBalance) : '';
  return `
  <div style="display: flex; flex-direction: column; width: 100%; box-sizing: border-box;">
  <div style="display: flex; font-size: 6pt; font-weight: 600;">
    <div style="display: flex; flex-direction: column;">
     <img src="/meezan-logo.png" style="width: 160px; height: 25px; margin-left: -12px" />
     <div style="display:flex; flex-direction: column; gap: 1px; color: #B21500;">
       <span>${accountInfo.branchName}</span>
       <span>${'NADIR HOUSE I I CHUNDRIGAR ROAD KARACHI'}</span>
       <span>QUICK ACCOUNT TRANSACTIONS</span>
     </div>
    </div>
    <div style="display: flex; margin-left: 100px">
      <span style="color: #B21500;">MEEZAN BANK LIMITED Print Date :</span>
      <span style="color: #0000ff; margin-left: 4px;">${accountInfo.printDate}</span>
    </div>
  </div>
  <div style="display: flex; margin-top: 4px; font-size: 6pt; font-weight: 600; color: #B21500;">
    <div style="display: flex; flex-direction: column;">
      <span style="margin-top: 20px">${accountInfo.accountTitle}</span>
      <div style="display: flex; flex-direction: column; margin-top: auto;">
      <span style="margin-top: auto;">${accountInfo.address}</span>
      <span style="margin-top: auto;">${accountInfo.address2}</span>
      </div>
    </div>
        
    <div style="display: flex; gap: 1px; color: #B21500; margin-left: 100px;">
      <div style="display: flex; flex-direction: column; gap: 1px;">
        <span style="height: 10px;">IBAN :</span>
        <span style="height: 10px;">Old Account No :</span>
        <span style="height: 10px;">Account No :</span>
        <span style="height: 10px;">Product :</span>
        <span style="height: 10px;">Currency :</span>
        <span style="height: 10px;">From Date :</span>
        <span style="height: 10px;">To Date :</span>
      </div>
      <div style="display: flex; flex-direction: column; gap: 1px;">
        <span style="height: 10px;">${accountInfo.iban}</span>
        <span style="height: 10px;">${accountInfo.oldAccountNo || ""}</span>
        <span style="height: 10px;">${accountInfo.accountNo}</span>
        <span style="height: 10px;">${accountInfo.product}</span>
        <span style="height: 10px;">${accountInfo.currency}</span>
        <span style="height: 10px;">${accountInfo.fromDate}</span>
        <span style="height: 10px;">${accountInfo.toDate}</span>
      </div>
    </div>

  </div>
  <div style="display: flex; font-size: 6pt; font-weight: 600; padding-left: 290px; width: 100%; flex-grow: 1;">
     <span style="color: #B21500;">Generated By : </span>
     <span style="color: #0000ff; margin-left: 40px;">${accountInfo.generatedBy}</span>
  </div>
  <div style="display: flex; font-size: 6pt; font-weight: 600; color: #B21500; width: 100%; margin-top:1px; margin-bottom:1px;">
  <span><= O P E N I N G - B A L A N C E =></span>
  <span style="margin-left: 265px;">${opening}</span>
  </div>
</div>
  `;
};

const generateTableHeader = () => {
  return `
    <thead>
      <tr style="">
        <th style="width: 85pt; text-align: left; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">Date(DD/MM)</th>
        <th style="width: 30pt; text-align: left; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">Value</th>
        <th style="width: 60pt; text-align: left; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">*******Doc.No*******</th>
        <th style="width: 115pt; text-align: left; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">***Particlar******</th>
        <th style="width: 60pt; text-align: right; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">*******Debit********</th>
        <th style="width: 60pt; text-align: right; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;">*******Credit*******</th>
        <th style="width: 75pt; text-align: right; font-size: 8pt; padding: 4pt 2pt; font-weight: 600; padding-right: 35pt;">******Balance*******</th>
        <th style="width: 75pt; text-align: center; font-size: 8pt; padding: 4pt 2pt; font-weight: 600;"></th>
      </tr>
    </thead>
  `;
};

const parseAmount = (val: string | number | undefined) => {
  if (!val && val !== 0) return 0;
  const s = typeof val === 'number' ? String(val) : (val || '').toString();
  const n = parseFloat(s.replace(/,/g, '').replace(/[^0-9.\-]/g, ''));
  return isNaN(n) ? 0 : n;
};

const toDDMMYY = (input?: string) => {
  if (!input) return '';
  const s = input.trim();
  // Match formats like 20-OCT-2025 produced by formatDate
  const m = s.match(/^(\d{1,2})-([A-Z]{3})-(\d{4})$/i);
  if (m) {
    const day = m[1].padStart(2, '0');
    const mon = m[2].toUpperCase();
    const map: Record<string,string> = {JAN:'01',FEB:'02',MAR:'03',APR:'04',MAY:'05',JUN:'06',JUL:'07',AUG:'08',SEP:'09',OCT:'10',NOV:'11',DEC:'12'};
    const mm = map[mon] || '01';
    const yy = m[3].slice(-2);
    return `${day}/${mm}/${yy}`;
  }

  // Match dd/mm/yyyy or dd-mm-yyyy
  const m2 = s.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{2,4})$/);
  if (m2) {
    const day = m2[1].padStart(2,'0');
    const mm = m2[2].padStart(2,'0');
    const yy = m2[3].length === 4 ? m2[3].slice(-2) : m2[3];
    return `${day}/${mm}/${yy}`;
  }

  // Fallback: try Date parse
  const d = new Date(s);
  if (!isNaN(d.getTime())) {
    const day = String(d.getDate()).padStart(2,'0');
    const mm = String(d.getMonth()+1).padStart(2,'0');
    const yy = String(d.getFullYear()).slice(-2);
    return `${day}/${mm}/${yy}`;
  }

  return s;
};

const generateNormalRow = (transaction: TransactionRow, showBalance: boolean, balanceValue: number) => {
  const particularsLines = transaction.particulars.split('\n');
  const particularsHtml = particularsLines.map((line) => `<div>${line}</div>`).join('');
  const balanceHtml = showBalance ? formatNumber(balanceValue) : '';

  return `
    <tr style="vertical-align: top;">
      <td style="width: 85pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 400">${toDDMMYY(transaction.date)}</td>
      <td style="width: 30pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 400">${toDDMMYY(transaction.valueDate || '')}</td>
      <td style="width: 60pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 400">${transaction.docNo || ''}</td>
      <td style="width: 115pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 400;"><p style="margin: 0; padding: 0; line-height: 24px">${particularsHtml}</p></td>
      <td style="width: 60pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 500;"><p style="margin: 0; padding: 0; text-align: right;">${transaction.debit ? formatNumber(transaction.debit) : ''}</p></td>
      <td style="width: 60pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 500;"><p style="margin: 0; padding: 0; text-align: right;">${transaction.credit ? formatNumber(transaction.credit) : ''}</p></td>
      <td style="width: 75pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 500;"><p style="margin: 0; padding: 0; text-align: right; padding-right: 35pt;">${balanceHtml}</p></td>
      <td style="width: 75pt; font-size: 8pt;padding: 4pt 2pt; font-weight: 400; text-align: center; color: #0000ff; text-decoration: underline;">Transaction D</td>
    </tr>
  `;
};

const generateSummarySection = (transactions: TransactionRow[], closingBalance: number) => {
  let totalDebit = 0;
  let totalCredit = 0;
  let debitCount = 0;
  let creditCount = 0;

  transactions.forEach((tx) => {
    if (!tx.isOpeningBalance && !tx.isClosingBalance) {
      if (tx.debit) {
        const val =
          typeof tx.debit === "string"
            ? parseFloat(tx.debit.replace(/,/g, ""))
            : tx.debit;
        if (!isNaN(val)) {
          totalDebit += Math.abs(val);
          debitCount++;
        }
      }
      if (tx.credit) {
        const val =
          typeof tx.credit === "string"
            ? parseFloat(tx.credit.replace(/,/g, ""))
            : tx.credit;
        if (!isNaN(val)) {
          totalCredit += Math.abs(val);
          creditCount++;
        }
      }
    }
  });

  return `
    <div style="margin-top: 4px; font-size: 6pt; color: #B21500; font-weight: 600;">
    <div style="display: flex; justify-content: space-between; margin-bottom: 8px;">
    <span><= C L O S I N G - B A L A N C E =></span>
     <span style="padding-right: 100pt;">${formatNumber(closingBalance)}</span>
    </div>
    <div style="display: flex; gap: 3px; margin-bottom: 1px;">
    <div style="width: 28.5%; height: 1px; background-color: #B21500;"></div>
    <div style="width: 28.5%; height: 1px; background-color: #B21500;"></div>
    <div style="width: 28.5%; height: 1px; background-color: #B21500;"></div>
    </div>
      <div style="display: flex; margin-bottom: 1px;">
        <div>Total No. of Credit Transaction</div>
        <div>________________________________________________________</div>
        <div style="margin-left: 2px;">${creditCount}</div>
      </div>
      <div style="display: flex; margin-bottom: 1px;">
        <div>Total No. of Debit Transaction</div>
        <div>________________________________________________________</div>
        <div style="margin-left: 2px;">${debitCount}</div>
      </div>
      <div style="display: flex; margin-bottom: 1px;">
        <div>Total Credit Turnover</div>
        <div>_______________________________________________________________</div>
        <div style="margin-left: 2px;">${formatNumber(totalCredit)}</div>
      </div>
      <div style="display: flex; margin-bottom: 1px;">
        <div>Total Debit Turnover</div>
        <div>_______________________________________________________________</div>
        <div style="margin-left: 2px;">${formatNumber(totalDebit)}</div>
      </div>
    </div>
  `;
};

const generateFooter = () => {
  return `<img src="/meezan-footer.png" style="width: 60%; margin-top: 2px;" />`;
};

export const generateMeezanHTML = (
  transactions: TransactionRow[],
  accountInfo: MeezanAccountInfo,
): string => {
  const tableHeader = generateTableHeader();
  // Determine opening balance (prefer accountInfo.openingBalance, fallback to opening tx)
  let openingBalance = 0;
  const openingTx = transactions.find((t) => t.isOpeningBalance);
  if (accountInfo.openingBalance) {
    openingBalance = parseAmount(accountInfo.openingBalance);
  } else if (openingTx && openingTx.balance) {
    openingBalance = parseAmount(openingTx.balance);
  }

  // prepare to compute running balance
  let currentBalance = openingBalance;

  // find last normal transaction index (exclude opening/closing)
  const normalIndexes: number[] = [];
  transactions.forEach((t, idx) => {
    if (!t.isOpeningBalance && !t.isClosingBalance) normalIndexes.push(idx);
  });
  const lastNormalIndex = normalIndexes.length ? normalIndexes[normalIndexes.length - 1] : -1;

  let tableRows = "";
  transactions.forEach((tx, idx) => {
    if (tx.isOpeningBalance) {
      const ob = openingBalance || parseAmount(tx.balance);
      currentBalance = ob;
      tableRows += `
        <tr>
          <td colspan="6" style="font-size: 8.5pt; font-weight: 600; padding: 8px 2px; color: #B21500;">&lt;= O P E N I N G - B A L A N C E =&gt;</td>
          <td style="text-align: right; font-size: 8.5pt; font-weight: 600; padding: 8px 2px; color: #000;">${formatNumber(currentBalance)}</td>
          <td></td>
        </tr>
      `;
      return;
    }

    if (tx.isClosingBalance) {
      tableRows += `
        <tr>
          <td colspan="7" style="text-align: right; font-size: 8.5pt; font-weight: 600; padding: 8px 2px; color: #000;">${formatNumber(currentBalance)}</td>
        </tr>
        <tr>
          <td colspan="6" style="font-size: 8.5pt; font-weight: 600; padding: 8px 2px; color: #B21500;">&lt;= C L O S I N G - B A L A N C E =&gt;</td>
          <td style="text-align: right; font-size: 8.5pt; font-weight: 600; padding: 8px 2px; color: #B21500;">${formatNumber(currentBalance)}</td>
          <td></td>
        </tr>
      `;
      return;
    }

    // normal transaction: update running balance
    const debit = parseAmount(tx.debit);
    const credit = parseAmount(tx.credit);
    currentBalance = currentBalance - debit + credit;

    const showBalance = idx === lastNormalIndex;
    tableRows += generateNormalRow(tx, showBalance, currentBalance);
  });

  const styles = `
    @page { 
      size: A4; 
      margin: 1cm; 
    }
    @media print {
      body { margin: 0; padding: 0; background: #fff; }
      .page-break { page-break-after: always; }
      tr { page-break-inside: avoid; }
      thead { display: table-header-group; }
    }
    body { 
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 0;
      background-color: #fff;
      color: #000;
    }
    .container {
      width: 100%;
      max-width: 1000px;
      margin: 0 auto;
      padding: 10px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      table-layout: fixed;
    }
    th, td {
      border: none;
      vertical-align: top;
    }
  `;

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Meezan Bank Statement</title>
      <style>${styles}</style>
    </head>
    <body>
      <div class="container">
        ${generateHeaderSection(accountInfo)}
        <table>
          ${tableHeader}
          <tbody>
            ${tableRows}
          </tbody>
        </table>
        ${generateSummarySection(transactions, currentBalance)}
        ${generateFooter()}
      </div>
    </body>
    </html>
  `;
};
